name: Comprehensive File Check

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  comprehensive-check:
    name: Comprehensive File Security Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for forbidden files with directory exclusions
        uses: mattkinnersley/forbid-files@v1
        with:
          files: |
            .env
            .env.local
            .env.development
            .env.production
            .env.staging
            .env.test
            config.json
            secrets.yaml
            secrets.yml
            credentials.json
            api-keys.txt
            private-key.pem
            *.p12
            *.pfx
            *.key
            *.pem
            .aws/credentials
            .ssh/id_rsa
            .ssh/id_ed25519
            *.log
            *.tmp
            *.temp
            .DS_Store
            Thumbs.db
            desktop.ini
            *.pyc
            *.pyo
            __pycache__
            .pytest_cache
            .coverage
            coverage.xml
            .nyc_output
            npm-debug.log*
            yarn-debug.log*
            yarn-error.log*
            .vscode/settings.json
            .idea/workspace.xml
            .idea/tasks.xml
            .idea/dictionaries
            .idea/shelf
            *.swp
            *.swo
            *~
            .#*
            \#*\#
          fail-fast: false
          ignore-case: true
          skip-directories: |
            .git
            .github
            node_modules
            vendor
            .venv
            venv
            env
            __pycache__
            .pytest_cache
            .tox
            .cache
            .parcel-cache
            .next
            .nuxt
            dist
            build
            out
            target
            .vscode
            .idea
            .vs
            .history
            .temp
            temp
            tmp
            logs
            coverage
            .nyc_output
            .sass-cache
            .gradle
            .m2
            .cargo
            .rustup
            htmlcov
            site-packages
            lib-cov
            bower_components
            jspm_packages
            web_modules

      - name: Report scan completion
        if: success()
        run: |
          echo "✅ Security scan completed successfully!"
          echo "No forbidden files found in the repository."

      - name: Report scan failure
        if: failure()
        run: |
          echo "❌ Security scan found forbidden files!"
          echo "Please review and remove the identified files before proceeding."
